"use strict";

/* =========================================================
   研究対象施設一覧

   店舗名・対象都道府県は研究対象リストとして管理する。
   住所・緯度経度・駐車場レイアウトは未登録のまま推測せず、
   今後の管理用Webアプリから facilityId をキーに追加する。
   ========================================================= */

const CATALOG_METADATA = Object.freeze({
  "total": 120,
  "prefectures": 12,
  "note": "研究対象として指定された中国・九州地方の店舗一覧。住所・座標・駐車場レイアウトは管理用Webアプリから追加する。"
});

const FACILITY_CATALOG = Object.freeze([
  {
    "id": "target_001",
    "name": "スーパーセンタートライアル 鳥取千代水店",
    "prefecture": "鳥取県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_001",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_002",
    "name": "トライアル 鳥取大杙店",
    "prefecture": "鳥取県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_002",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_003",
    "name": "トライアル 叶店",
    "prefecture": "鳥取県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_003",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_004",
    "name": "トライアル 米子大谷店",
    "prefecture": "鳥取県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_004",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_005",
    "name": "トライアル 琴浦店",
    "prefecture": "鳥取県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_005",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_006",
    "name": "トライアル 境港店",
    "prefecture": "鳥取県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_006",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_007",
    "name": "ラ・ムー 鳥取店",
    "prefecture": "鳥取県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_007",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_008",
    "name": "ラ・ムー 倉吉店",
    "prefecture": "鳥取県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_008",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_009",
    "name": "ホームプラザナフコ 東鳥取店",
    "prefecture": "鳥取県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_009",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_010",
    "name": "カインズFC 鳥取店",
    "prefecture": "鳥取県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_010",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_011",
    "name": "トライアル 松江店",
    "prefecture": "島根県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_011",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_012",
    "name": "トライアル 出雲白枝店",
    "prefecture": "島根県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_012",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_013",
    "name": "トライアル 出雲斐川店",
    "prefecture": "島根県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_013",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_014",
    "name": "トライアル 雲南店",
    "prefecture": "島根県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_014",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_015",
    "name": "トライアル 浜田店",
    "prefecture": "島根県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_015",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_016",
    "name": "トライアル 益田店",
    "prefecture": "島根県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_016",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_017",
    "name": "トライアル 大田店",
    "prefecture": "島根県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_017",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_018",
    "name": "ラ・ムー 安来店",
    "prefecture": "島根県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_018",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_019",
    "name": "ホームプラザナフコ 松江店",
    "prefecture": "島根県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_019",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_020",
    "name": "ホームプラザナフコ 北出雲店",
    "prefecture": "島根県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_020",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_021",
    "name": "マルナカ 中井町店",
    "prefecture": "岡山県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_021",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_022",
    "name": "ラ・ムー 岡山中央店",
    "prefecture": "岡山県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_022",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_023",
    "name": "トライアル 岡山豊浜店",
    "prefecture": "岡山県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_023",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_024",
    "name": "カインズ 岡山南店",
    "prefecture": "岡山県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_024",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_025",
    "name": "マルナカ マスカット店",
    "prefecture": "岡山県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_025",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_026",
    "name": "マルナカ 山陽店",
    "prefecture": "岡山県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_026",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_027",
    "name": "MrMax 岡山西店",
    "prefecture": "岡山県",
    "municipality": "",
    "address": "",
    "category": "discount-store",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_027",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_028",
    "name": "トライアル 東岡山店",
    "prefecture": "岡山県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_028",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_029",
    "name": "コメリパワー 津山店",
    "prefecture": "岡山県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_029",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_030",
    "name": "マルナカ 連島店",
    "prefecture": "岡山県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_030",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_031",
    "name": "トライアル 大竹店",
    "prefecture": "広島県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_031",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_032",
    "name": "ラ・ムー 松永店",
    "prefecture": "広島県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_032",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_033",
    "name": "ラ・ムー 中野東店",
    "prefecture": "広島県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_033",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_034",
    "name": "MrMax 八本松店",
    "prefecture": "広島県",
    "municipality": "",
    "address": "",
    "category": "discount-store",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_034",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_035",
    "name": "ホームプラザナフコ 東広島店",
    "prefecture": "広島県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_035",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_036",
    "name": "ホームプラザナフコ 三次店",
    "prefecture": "広島県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_036",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_037",
    "name": "ホームプラザナフコ 尾道店",
    "prefecture": "広島県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_037",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_038",
    "name": "ホームプラザナフコ 黒瀬店",
    "prefecture": "広島県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_038",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_039",
    "name": "ホームプラザナフコ 庄原店",
    "prefecture": "広島県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_039",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_040",
    "name": "ホームプラザナフコ 吉田店",
    "prefecture": "広島県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_040",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_041",
    "name": "トライアル 山口小郡店",
    "prefecture": "山口県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_041",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_042",
    "name": "トライアル 長府店",
    "prefecture": "山口県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_042",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_043",
    "name": "トライアル 周南店",
    "prefecture": "山口県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_043",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_044",
    "name": "トライアル 新下関店",
    "prefecture": "山口県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_044",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_045",
    "name": "MrMax 山口店",
    "prefecture": "山口県",
    "municipality": "",
    "address": "",
    "category": "discount-store",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_045",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_046",
    "name": "MrMax 末武店",
    "prefecture": "山口県",
    "municipality": "",
    "address": "",
    "category": "discount-store",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_046",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_047",
    "name": "ホームプラザナフコ 山口店",
    "prefecture": "山口県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_047",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_048",
    "name": "ホームプラザナフコ 周南店",
    "prefecture": "山口県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_048",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_049",
    "name": "ホームプラザナフコ 防府店",
    "prefecture": "山口県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_049",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_050",
    "name": "ホームプラザナフコ 南岩国店",
    "prefecture": "山口県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_050",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_051",
    "name": "マルキョウ 花見店",
    "prefecture": "福岡県",
    "municipality": "古賀市",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_051",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_052",
    "name": "トライアル 古賀花見店",
    "prefecture": "福岡県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_052",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_053",
    "name": "ハンズマン 大野城店",
    "prefecture": "福岡県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_053",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_054",
    "name": "ハンズマン くさみ店",
    "prefecture": "福岡県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_054",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_055",
    "name": "カインズ 福岡新宮店",
    "prefecture": "福岡県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_055",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_056",
    "name": "トライアル 宗像店",
    "prefecture": "福岡県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_056",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_057",
    "name": "トライアル 直方店",
    "prefecture": "福岡県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_057",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_058",
    "name": "コメリパワー 飯塚店",
    "prefecture": "福岡県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_058",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_059",
    "name": "MrMax 宗像店",
    "prefecture": "福岡県",
    "municipality": "",
    "address": "",
    "category": "discount-store",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_059",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_060",
    "name": "マルキョウ 宗像店",
    "prefecture": "福岡県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_060",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_061",
    "name": "トライアル 佐賀大和店",
    "prefecture": "佐賀県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_061",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_062",
    "name": "トライアル 嬉野店",
    "prefecture": "佐賀県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_062",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_063",
    "name": "トライアル 三日月店",
    "prefecture": "佐賀県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_063",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_064",
    "name": "TRIAL smart 伊万里店",
    "prefecture": "佐賀県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_064",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_065",
    "name": "トライアル 武雄富岡店",
    "prefecture": "佐賀県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_065",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_066",
    "name": "マルキョウ 神埼店",
    "prefecture": "佐賀県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_066",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_067",
    "name": "マルキョウ 武雄店",
    "prefecture": "佐賀県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_067",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_068",
    "name": "MrMax 北茂安店",
    "prefecture": "佐賀県",
    "municipality": "",
    "address": "",
    "category": "discount-store",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_068",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_069",
    "name": "ホームプラザナフコ 武雄店",
    "prefecture": "佐賀県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_069",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_070",
    "name": "ホームプラザナフコ 唐津店",
    "prefecture": "佐賀県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_070",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_071",
    "name": "トライアル 佐々店",
    "prefecture": "長崎県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_071",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_072",
    "name": "TRIAL smart 東長崎店",
    "prefecture": "長崎県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_072",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_073",
    "name": "TRIAL smart 佐世保大塔店",
    "prefecture": "長崎県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_073",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_074",
    "name": "トライアル 佐世保大和店",
    "prefecture": "長崎県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_074",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_075",
    "name": "トライアル 島原店",
    "prefecture": "長崎県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_075",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_076",
    "name": "トライアル 大村店",
    "prefecture": "長崎県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_076",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_077",
    "name": "トライアル 諫早店",
    "prefecture": "長崎県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_077",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_078",
    "name": "トライアル 時津店",
    "prefecture": "長崎県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_078",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_079",
    "name": "マルキョウ 大宮店",
    "prefecture": "長崎県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_079",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_080",
    "name": "ホームプラザナフコ 時津店",
    "prefecture": "長崎県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_080",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_081",
    "name": "ハンズマン 画図店",
    "prefecture": "熊本県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_081",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_082",
    "name": "ハンズマン 菊陽店",
    "prefecture": "熊本県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_082",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_083",
    "name": "メガセンタートライアル 大津店",
    "prefecture": "熊本県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_083",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_084",
    "name": "メガセンタートライアル 荒尾店",
    "prefecture": "熊本県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_084",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_085",
    "name": "トライアル 宇土店",
    "prefecture": "熊本県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_085",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_086",
    "name": "トライアル 八代店",
    "prefecture": "熊本県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_086",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_087",
    "name": "カインズ 熊本宇土店",
    "prefecture": "熊本県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_087",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_088",
    "name": "マルキョウ 植木店",
    "prefecture": "熊本県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_088",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_089",
    "name": "マルキョウ 合志店",
    "prefecture": "熊本県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_089",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_090",
    "name": "マルキョウ 玉名店",
    "prefecture": "熊本県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_090",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_091",
    "name": "ハンズマン わさだ店",
    "prefecture": "大分県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_091",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_092",
    "name": "メガセンタートライアル わさだ店",
    "prefecture": "大分県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_092",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_093",
    "name": "トライアル 皆春店",
    "prefecture": "大分県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_093",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_094",
    "name": "トライアル 敷戸店",
    "prefecture": "大分県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_094",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_095",
    "name": "トライアル 日田店",
    "prefecture": "大分県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_095",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_096",
    "name": "トライアル 別府店",
    "prefecture": "大分県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_096",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_097",
    "name": "トライアル 中津店",
    "prefecture": "大分県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_097",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_098",
    "name": "マルキョウ 皆春店",
    "prefecture": "大分県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_098",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_099",
    "name": "マルキョウ 中津店",
    "prefecture": "大分県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_099",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_100",
    "name": "MrMax 宇佐店",
    "prefecture": "大分県",
    "municipality": "",
    "address": "",
    "category": "discount-store",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_100",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_101",
    "name": "ハンズマン 加納店",
    "prefecture": "宮崎県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_101",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_102",
    "name": "ハンズマン 新名爪店",
    "prefecture": "宮崎県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_102",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_103",
    "name": "ハンズマン 柳丸店",
    "prefecture": "宮崎県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_103",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_104",
    "name": "ハンズマン 吉尾店",
    "prefecture": "宮崎県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_104",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_105",
    "name": "トライアル 加納店",
    "prefecture": "宮崎県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_105",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_106",
    "name": "トライアル 宮崎恒久店",
    "prefecture": "宮崎県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_106",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_107",
    "name": "トライアル 都城都北店",
    "prefecture": "宮崎県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_107",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_108",
    "name": "トライアル 小林店",
    "prefecture": "宮崎県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_108",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_109",
    "name": "メガセンタートライアル 日向店",
    "prefecture": "宮崎県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_109",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_110",
    "name": "トライアル 日南店",
    "prefecture": "宮崎県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_110",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_111",
    "name": "ハンズマン 宇宿店",
    "prefecture": "鹿児島県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_111",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_112",
    "name": "ハンズマン 国分店",
    "prefecture": "鹿児島県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_112",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_113",
    "name": "トライアル 東開店",
    "prefecture": "鹿児島県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_113",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_114",
    "name": "トライアル 隼人店",
    "prefecture": "鹿児島県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_114",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_115",
    "name": "トライアル 指宿店",
    "prefecture": "鹿児島県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_115",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_116",
    "name": "トライアル 鹿屋店",
    "prefecture": "鹿児島県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_116",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_117",
    "name": "トライアル 鹿屋上野町店",
    "prefecture": "鹿児島県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_117",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_118",
    "name": "トライアル 出水黄金店",
    "prefecture": "鹿児島県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_118",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_119",
    "name": "トライアル 加治木店",
    "prefecture": "鹿児島県",
    "municipality": "",
    "address": "",
    "category": "supermarket",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_119",
    "targetBuildingId": null,
    "isDemo": false
  },
  {
    "id": "target_120",
    "name": "ホームプラザナフコ 鹿児島東開店",
    "prefecture": "鹿児島県",
    "municipality": "",
    "address": "",
    "category": "home-center",
    "latitude": null,
    "longitude": null,
    "layoutId": "target_120",
    "targetBuildingId": null,
    "isDemo": false
  }
]);
