"use strict";

/* =========================================================
   研究対象施設一覧

   - 管理画面と同じ120店舗を同じ facilityId で保持する。
   - 施設選択、現在地からの距離計算、駐車場レイアウト参照に使用する。
   - 全120店舗に固定緯度経度を登録済み。
   - facilityRevision が2以上の店舗は旧対象店舗からの差し替えであり、
     旧レイアウトを誤って表示しないための識別にも使用する。
   ========================================================= */

const CATALOG_METADATA = Object.freeze({
  "total": 121,
  "researchTargetCount": 120,
  "activeResearchSampleCount": 49,
  "archivedCandidateCount": 71,
  "testFacilityCount": 1,
  "prefectures": 12,
  "note": "研究候補120施設を保持しつつ、通常表示は49施設に整理。各県は大型比較1＋ドラッグストア1＋ファミレス1＋道の駅1を基本とし、岡山県のみ既存研究対象のマルナカ中井町店を追加。旧候補71件は予備として非表示。",
  "locationAuditDate": "2026-09-28",
  "locationVerifiedCount": 120,
  "fixedCoordinateCount": 120,
  "parkingSelectionAuditDate": "2026-09-29",
  "okayamaSmallParkingCount": 8,
  "okayamaRetainedLargeStoreCount": 2
});

const FACILITY_CATALOG = Object.freeze([
// ----- 鳥取県 -----
{
  "id": "target_001",
  "name": "ドラッグストアコスモス 南昭和店",
  "prefecture": "鳥取県",
  "municipality": "倉吉市",
  "address": "鳥取県倉吉市南昭和町71",
  "category": "drugstore",
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_001",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_002",
  "name": "ガスト 鳥取南店",
  "prefecture": "鳥取県",
  "municipality": "鳥取市",
  "address": "鳥取県鳥取市正蓮寺49-1",
  "category": "restaurant",
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_002",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_003",
  "name": "道の駅 西いなば気楽里",
  "prefecture": "鳥取県",
  "municipality": "鳥取市",
  "address": "鳥取県鳥取市鹿野町岡木280-3",
  "category": "roadside-station",
  "parkingCapacity": 122,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_003",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_004",
  "name": "トライアル 米子大谷店",
  "prefecture": "鳥取県",
  "municipality": "米子市",
  "address": "鳥取県米子市大谷町28",
  "category": "supermarket",
  "latitude": 35.418817,
  "longitude": 133.3339386,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "公式MAP座標",
  "operatingStatus": "active",
  "layoutId": "target_004",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_005",
  "name": "トライアル 琴浦店",
  "prefecture": "鳥取県",
  "municipality": "東伯郡琴浦町",
  "address": "鳥取県東伯郡琴浦町大字逢束1273",
  "category": "supermarket",
  "latitude": 35.503398,
  "longitude": 133.697094,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "公式MAP座標",
  "operatingStatus": "active",
  "layoutId": "target_005",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_006",
  "name": "トライアル 境港店",
  "prefecture": "鳥取県",
  "municipality": "境港市",
  "address": "鳥取県境港市夕日ヶ丘2丁目8",
  "category": "supermarket",
  "latitude": 35.508682,
  "longitude": 133.221312,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "公式MAP座標",
  "operatingStatus": "active",
  "layoutId": "target_006",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_007",
  "name": "ラ・ムー 鳥取店",
  "prefecture": "鳥取県",
  "municipality": "鳥取市",
  "address": "鳥取県鳥取市安長217番地1",
  "category": "supermarket",
  "latitude": 35.5107217,
  "longitude": 134.2035329,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "大黒天物産公式店舗情報・公的資料",
  "locationSourceUrl": "https://www.dkt-s.com/brand.html",
  "coordinateSource": "Yahoo!マップ地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_007",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_008",
  "name": "ラ・ムー 倉吉店",
  "prefecture": "鳥取県",
  "municipality": "倉吉市",
  "address": "鳥取県倉吉市河北町125-1",
  "category": "supermarket",
  "latitude": 35.4666609,
  "longitude": 133.8436615,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "大黒天物産公式店舗情報・公的資料",
  "locationSourceUrl": "https://www.dkt-s.com/brand.html",
  "coordinateSource": "Yahoo!マップ地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_008",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_009",
  "name": "ホームプラザナフコ 東鳥取店",
  "prefecture": "鳥取県",
  "municipality": "鳥取市",
  "address": "鳥取県鳥取市国府町新通り4-408-16",
  "category": "home-center",
  "latitude": 35.4826455,
  "longitude": 134.2540126,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "ナフコ公式店舗情報",
  "locationSourceUrl": "https://www.nafco.life/shop_list/",
  "coordinateSource": "Yahoo!マップ地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_009",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_010",
  "name": "カインズFC 鳥取店",
  "prefecture": "鳥取県",
  "municipality": "鳥取市",
  "address": "鳥取県鳥取市古海字西加路田590",
  "category": "home-center",
  "latitude": 35.49624303,
  "longitude": 134.20397782,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "カインズ公式店舗情報",
  "locationSourceUrl": "https://map.cainz.com/",
  "coordinateSource": "Yahoo!マップ地点（公式住所照合）",
  "operatingStatus": "active",
  "officialName": "カインズ 鳥取店",
  "layoutId": "target_010",
  "targetBuildingId": null,
  "isDemo": false,
  "sampleRole": "large-comparison"
},
// ----- 島根県 -----
{
  "id": "target_011",
  "name": "ドラッグストアコスモス 大田店",
  "prefecture": "島根県",
  "municipality": "大田市",
  "address": "島根県大田市長久町長久イ588-1",
  "category": "drugstore",
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_011",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_012",
  "name": "ガスト 島根大田店",
  "prefecture": "島根県",
  "municipality": "大田市",
  "address": "島根県大田市長久町土江97",
  "category": "restaurant",
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_012",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_013",
  "name": "道の駅 湯の川",
  "prefecture": "島根県",
  "municipality": "出雲市",
  "address": "島根県出雲市斐川町学頭825-2",
  "category": "roadside-station",
  "parkingCapacity": 101,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_013",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_014",
  "name": "トライアル 雲南店",
  "prefecture": "島根県",
  "municipality": "雲南市",
  "address": "島根県雲南市加茂町加茂中2-1",
  "category": "supermarket",
  "latitude": 35.34912,
  "longitude": 132.902262,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "公式MAP座標",
  "operatingStatus": "active",
  "layoutId": "target_014",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_015",
  "name": "トライアル 浜田店",
  "prefecture": "島根県",
  "municipality": "浜田市",
  "address": "島根県浜田市周布町イ61-1",
  "category": "supermarket",
  "latitude": 34.86299133,
  "longitude": 132.0260925,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "公式MAP座標",
  "operatingStatus": "active",
  "layoutId": "target_015",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_016",
  "name": "トライアル 益田店",
  "prefecture": "島根県",
  "municipality": "益田市",
  "address": "島根県益田市須子町32-7",
  "category": "supermarket",
  "latitude": 34.67375,
  "longitude": 131.826664,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "公式MAP座標",
  "operatingStatus": "active",
  "layoutId": "target_016",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_017",
  "name": "トライアル 大田店",
  "prefecture": "島根県",
  "municipality": "大田市",
  "address": "島根県大田市長久町長久イ309番地2",
  "category": "supermarket",
  "latitude": 35.20224827467981,
  "longitude": 132.48607219957708,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "公式MAP座標",
  "operatingStatus": "active",
  "layoutId": "target_017",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_018",
  "name": "ラ・ムー 安来店",
  "prefecture": "島根県",
  "municipality": "安来市",
  "address": "島根県安来市飯島町396番地",
  "category": "supermarket",
  "latitude": 35.4343251,
  "longitude": 133.2400764,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "大黒天物産公式店舗情報・公的資料",
  "locationSourceUrl": "https://www.dkt-s.com/brand.html",
  "coordinateSource": "Yahoo!マップ地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_018",
  "targetBuildingId": null,
  "isDemo": false,
  "sampleRole": "large-comparison"
},
{
  "id": "target_019",
  "name": "ホームプラザナフコ 松江店",
  "prefecture": "島根県",
  "municipality": "松江市",
  "address": "島根県松江市竹矢町1850-15",
  "category": "home-center",
  "latitude": 35.4393287,
  "longitude": 133.119498,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "ナフコ公式店舗情報",
  "locationSourceUrl": "https://www.nafco.life/shop_list/",
  "coordinateSource": "Yahoo!マップ地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_019",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_020",
  "name": "ホームプラザナフコ 北出雲店",
  "prefecture": "島根県",
  "municipality": "出雲市",
  "address": "島根県出雲市江田町47-4",
  "category": "home-center",
  "latitude": 35.3846515,
  "longitude": 132.7345767,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "ナフコ公式店舗情報",
  "locationSourceUrl": "https://www.nafco.life/shop_list/",
  "coordinateSource": "Yahoo!マップ地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_020",
  "targetBuildingId": null,
  "isDemo": false
},
// ----- 岡山県 -----
{
  "id": "home-test-001",
  "name": "自宅テスト用",
  "prefecture": "岡山県",
  "municipality": "岡山市",
  "address": "岡山県岡山市北区（自宅テスト用・詳細非公開）",
  "category": "experiment",
  "locationVerified": false,
  "coordinateSource": "利用端末の現在地から登録。正確な座標は公開リポジトリ・Supabaseへ保存しない",
  "operatingStatus": "active",
  "layoutId": "home-test-001",
  "targetBuildingId": null,
  "isDemo": false,
  "isPrivateTest": true,
  "requiresLocalCalibration": true
},

{
  "id": "target_021",
  "name": "マルナカ 中井町店",
  "prefecture": "岡山県",
  "municipality": "岡山市",
  "address": "岡山県岡山市北区中井町1丁目280-2",
  "category": "supermarket",
  "latitude": 34.6818257,
  "longitude": 133.9286279,
  "parkingCapacity": 12,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "フジ公式店舗情報",
  "locationSourceUrl": "https://www.the-fuji.com/mv/store/category/okayama/",
  "coordinateSource": "Yahoo!マップ地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_021",
  "targetBuildingId": null,
  "isDemo": false,
  "sampleRole": "small-medium-core"
},
{
  "id": "target_022",
  "name": "ラ・ムー 岡山中央店",
  "displayName": "ラ・ムータウン岡山中央",
  "prefecture": "岡山県",
  "municipality": "岡山市",
  "address": "岡山県岡山市北区中井町2丁目5番61号",
  "category": "shopping-center",
  "latitude": 34.6841837,
  "longitude": 133.9332219,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "大黒天物産公式店舗情報・公的資料",
  "locationSourceUrl": "https://www.dkt-s.com/brand.html",
  "coordinateSource": "Yahoo!マップ地点（公式住所照合）",
  "operatingStatus": "active",
  "facilityRevision": 3,
  "replacementReason": "研究対象見直し後も比較対象として残すため再登録",
  "layoutId": "target_022",
  "targetBuildingId": null,
  "isDemo": false,
  "sampleRole": "large-comparison",
  "siteType": "compound",
  "parkingCapacity": 392,
  "destinations": [
    { "id": "lamu", "name": "ラ・ムー 岡山中央店", "buildingId": "building_lamu" },
    { "id": "uniqlo", "name": "ユニクロ", "buildingId": "building_uniqlo" },
    { "id": "gu", "name": "GU", "buildingId": "building_gu" },
    { "id": "zagzag", "name": "ザグザグ", "buildingId": "building_zagzag" },
    { "id": "nishimatsuya", "name": "西松屋", "buildingId": "building_nishimatsuya" },
    { "id": "daiso", "name": "ダイソー", "buildingId": "building_daiso" }
  ]
},
{
  "id": "target_023",
  "name": "トライアル 岡山豊浜店",
  "prefecture": "岡山県",
  "municipality": "岡山市",
  "address": "岡山県岡山市南区豊浜町13番68号",
  "category": "supermarket",
  "latitude": 34.63085566541993,
  "longitude": 133.93570388945932,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "公式MAP座標",
  "operatingStatus": "active",
  "facilityRevision": 3,
  "replacementReason": "研究対象見直し後も比較対象として残すため再登録",
  "layoutId": "target_023",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_024",
  "name": "マルナカ 芳田店",
  "prefecture": "岡山県",
  "municipality": "岡山市",
  "address": "岡山県岡山市南区西市120-6",
  "category": "supermarket",
  "latitude": 34.6295918,
  "longitude": 133.9053729,
  "parkingCapacity": 36,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "フジ公式店舗情報",
  "locationSourceUrl": "https://www.the-fuji.com/mv/store/category/okayama/",
  "coordinateSource": "MapFan地点（公式住所照合）",
  "operatingStatus": "active",
  "facilityRevision": 2,
  "replacementReason": "国土地理院空中写真で店舗が確認しにくい新規開業店を外し、小規模駐車場へ置換（旧：カインズ 岡山南店）",
  "layoutId": "target_024",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_025",
  "name": "マルナカ 総社店",
  "prefecture": "岡山県",
  "municipality": "総社市",
  "address": "岡山県総社市総社2丁目2-29",
  "category": "supermarket",
  "latitude": 34.6740105,
  "longitude": 133.7517838,
  "parkingCapacity": 39,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "フジ公式店舗情報",
  "locationSourceUrl": "https://www.the-fuji.com/mv/store/category/okayama/",
  "coordinateSource": "MapFan地点（公式住所照合）",
  "operatingStatus": "active",
  "facilityRevision": 2,
  "replacementReason": "研究対象を小規模駐車場中心へ見直したため置換（旧：マルナカ マスカット店）",
  "layoutId": "target_025",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_026",
  "name": "マルナカ 大元店",
  "prefecture": "岡山県",
  "municipality": "岡山市",
  "address": "岡山県岡山市北区西古松2丁目1-104",
  "category": "supermarket",
  "latitude": 34.6466527,
  "longitude": 133.9104641,
  "parkingCapacity": 41,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "フジ公式店舗情報",
  "locationSourceUrl": "https://www.the-fuji.com/mv/store/category/okayama/",
  "coordinateSource": "MapFan地点（公式住所照合）",
  "operatingStatus": "active",
  "facilityRevision": 2,
  "replacementReason": "研究対象を小規模駐車場中心へ見直したため置換（旧：マルナカ 山陽店）",
  "layoutId": "target_026",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_027",
  "name": "マルナカ 雄町店",
  "prefecture": "岡山県",
  "municipality": "岡山市",
  "address": "岡山県岡山市中区雄町153-5",
  "category": "supermarket",
  "latitude": 34.6847823,
  "longitude": 133.9702731,
  "parkingCapacity": 58,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "フジ公式店舗情報",
  "locationSourceUrl": "https://www.the-fuji.com/mv/store/category/okayama/",
  "coordinateSource": "MapFan地点（公式住所照合）",
  "operatingStatus": "active",
  "facilityRevision": 2,
  "replacementReason": "研究対象を小規模駐車場中心へ見直したため置換（旧：MrMax 岡山西店）",
  "layoutId": "target_027",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_028",
  "name": "ドラッグストアコスモス 津高店",
  "prefecture": "岡山県",
  "municipality": "岡山市",
  "address": "岡山県岡山市北区横井上226",
  "category": "drugstore",
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_028",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_029",
  "name": "ガスト 岡山下中野店",
  "prefecture": "岡山県",
  "municipality": "岡山市",
  "address": "岡山県岡山市北区下中野466-3",
  "category": "restaurant",
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_029",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_030",
  "name": "道の駅 久米の里",
  "prefecture": "岡山県",
  "municipality": "津山市",
  "address": "岡山県津山市宮尾563-1",
  "category": "roadside-station",
  "parkingCapacity": 46,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_030",
  "targetBuildingId": null,
  "isDemo": false
},
// ----- 広島県 -----
{
  "id": "target_031",
  "name": "ドラッグストアコスモス 福山新涯店",
  "prefecture": "広島県",
  "municipality": "福山市",
  "address": "広島県福山市新涯町2丁目8-12",
  "category": "drugstore",
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_031",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_032",
  "name": "ガスト 東広島西条インター店",
  "prefecture": "広島県",
  "municipality": "東広島市",
  "address": "広島県東広島市西条町吉行855-5",
  "category": "restaurant",
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_032",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_033",
  "name": "道の駅 たけはら",
  "prefecture": "広島県",
  "municipality": "竹原市",
  "address": "広島県竹原市本町1丁目1-1",
  "category": "roadside-station",
  "parkingCapacity": 48,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_033",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_034",
  "name": "MrMax 八本松店",
  "prefecture": "広島県",
  "municipality": "東広島市",
  "address": "広島県東広島市八本松西一丁目12番23号",
  "category": "discount-store",
  "latitude": 34.44521283,
  "longitude": 132.68203949,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "MrMax公式店舗情報",
  "locationSourceUrl": "https://www.mrmax.co.jp/shops/",
  "coordinateSource": "Yahoo!マップ地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_034",
  "targetBuildingId": null,
  "isDemo": false,
  "sampleRole": "large-comparison"
},
{
  "id": "target_035",
  "name": "ホームプラザナフコ 東広島店",
  "prefecture": "広島県",
  "municipality": "東広島市",
  "address": "広島県東広島市西条下見7-4-1",
  "category": "home-center",
  "latitude": 34.4066789,
  "longitude": 132.7098017,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "ナフコ公式店舗情報",
  "locationSourceUrl": "https://www.nafco.life/shop_list/",
  "coordinateSource": "Yahoo!マップ地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_035",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_036",
  "name": "ホームプラザナフコ 三次店",
  "prefecture": "広島県",
  "municipality": "三次市",
  "address": "広島県三次市東酒屋町380-1",
  "category": "home-center",
  "latitude": 34.7814769,
  "longitude": 132.8767107,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "ナフコ公式店舗情報",
  "locationSourceUrl": "https://www.nafco.life/shop_list/",
  "coordinateSource": "Yahoo!マップ地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_036",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_037",
  "name": "ホームプラザナフコ 尾道店",
  "prefecture": "広島県",
  "municipality": "尾道市",
  "address": "広島県尾道市東尾道9-5",
  "category": "home-center",
  "latitude": 34.4205662,
  "longitude": 133.2332519,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "ナフコ公式店舗情報",
  "locationSourceUrl": "https://www.nafco.life/shop_list/",
  "coordinateSource": "Yahoo!マップ地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_037",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_038",
  "name": "ホームプラザナフコ 黒瀬店",
  "prefecture": "広島県",
  "municipality": "東広島市",
  "address": "広島県東広島市黒瀬春日野1-132-4",
  "category": "home-center",
  "latitude": 34.3312556,
  "longitude": 132.6578446,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "ナフコ公式店舗情報",
  "locationSourceUrl": "https://www.nafco.life/shop_list/",
  "coordinateSource": "Yahoo!マップ地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_038",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_039",
  "name": "ホームプラザナフコ 庄原店",
  "prefecture": "広島県",
  "municipality": "庄原市",
  "address": "広島県庄原市板橋町278-1",
  "category": "home-center",
  "latitude": 34.84795905,
  "longitude": 133.01995694,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "ナフコ公式店舗情報",
  "locationSourceUrl": "https://www.nafco.life/shop_list/",
  "coordinateSource": "Mapion地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_039",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_040",
  "name": "ホームプラザナフコ 吉田店",
  "prefecture": "広島県",
  "municipality": "安芸高田市",
  "address": "広島県安芸高田市吉田町常友618-1",
  "category": "home-center",
  "latitude": 34.6550388,
  "longitude": 132.6915307,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "ナフコ公式店舗情報",
  "locationSourceUrl": "https://www.nafco.life/shop_list/",
  "coordinateSource": "Yahoo!マップ地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_040",
  "targetBuildingId": null,
  "isDemo": false
},
// ----- 山口県 -----
{
  "id": "target_041",
  "name": "ドラッグストアコスモス 新山口駅店",
  "prefecture": "山口県",
  "municipality": "山口市",
  "address": "山口県山口市小郡平成町1-31",
  "category": "drugstore",
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_041",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_042",
  "name": "ガスト 山口小郡店",
  "prefecture": "山口県",
  "municipality": "山口市",
  "address": "山口県山口市小郡前田町3-24",
  "category": "restaurant",
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_042",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_043",
  "name": "道の駅 あいお",
  "prefecture": "山口県",
  "municipality": "山口市",
  "address": "山口県山口市秋穂東1520-4",
  "category": "roadside-station",
  "parkingCapacity": 18,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_043",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_044",
  "name": "トライアル 新下関店",
  "prefecture": "山口県",
  "municipality": "下関市",
  "address": "山口県下関市一の宮町1丁目2-27",
  "category": "supermarket",
  "latitude": 34.004688,
  "longitude": 130.9451,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "公式MAP座標",
  "operatingStatus": "active",
  "layoutId": "target_044",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_045",
  "name": "MrMax 山口店",
  "prefecture": "山口県",
  "municipality": "山口市",
  "address": "山口県山口市黒川82番1",
  "category": "discount-store",
  "latitude": 34.13617603,
  "longitude": 131.43420518,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "MrMax公式店舗情報",
  "locationSourceUrl": "https://www.mrmax.co.jp/shops/",
  "coordinateSource": "Yahoo!マップ地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_045",
  "targetBuildingId": null,
  "isDemo": false,
  "sampleRole": "large-comparison"
},
{
  "id": "target_046",
  "name": "MrMax 末武店",
  "prefecture": "山口県",
  "municipality": "下松市",
  "address": "山口県下松市美里町2丁目7番1号",
  "category": "discount-store",
  "latitude": 34.02716699,
  "longitude": 131.86337845,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "MrMax公式店舗情報",
  "locationSourceUrl": "https://www.mrmax.co.jp/shops/",
  "coordinateSource": "Yahoo!マップ地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_046",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_047",
  "name": "ホームプラザナフコ 山口店",
  "prefecture": "山口県",
  "municipality": "山口市",
  "address": "山口県山口市朝田780-3",
  "category": "home-center",
  "latitude": 34.1478279,
  "longitude": 131.4328661,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "ナフコ公式店舗情報",
  "locationSourceUrl": "https://www.nafco.life/shop_list/",
  "coordinateSource": "Yahoo!マップ地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_047",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_048",
  "name": "ホームプラザナフコ 周南店",
  "prefecture": "山口県",
  "municipality": "周南市",
  "address": "山口県周南市久米1503-1",
  "category": "home-center",
  "latitude": 34.0388377,
  "longitude": 131.8462437,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "ナフコ公式店舗情報",
  "locationSourceUrl": "https://www.nafco.life/shop_list/",
  "coordinateSource": "Yahoo!マップ地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_048",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_049",
  "name": "ホームプラザナフコ 防府店",
  "prefecture": "山口県",
  "municipality": "防府市",
  "address": "山口県防府市西仁井令1-7-1",
  "category": "home-center",
  "latitude": 34.0515648,
  "longitude": 131.549874,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "ナフコ公式店舗情報",
  "locationSourceUrl": "https://www.nafco.life/shop_list/",
  "coordinateSource": "Yahoo!マップ地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_049",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_050",
  "name": "ホームプラザナフコ 南岩国店",
  "prefecture": "山口県",
  "municipality": "岩国市",
  "address": "山口県岩国市南岩国町3-32-2",
  "category": "home-center",
  "latitude": 34.1355368,
  "longitude": 132.1953691,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "ナフコ公式店舗情報",
  "locationSourceUrl": "https://www.nafco.life/shop_list/",
  "coordinateSource": "Yahoo!マップ地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_050",
  "targetBuildingId": null,
  "isDemo": false
},
// ----- 福岡県 -----
{
  "id": "target_051",
  "name": "マルキョウ 花見店",
  "prefecture": "福岡県",
  "municipality": "古賀市",
  "address": "福岡県古賀市花見東4丁目1-2",
  "category": "supermarket",
  "latitude": 33.7487776,
  "longitude": 130.4717951,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "マルキョウ公式店舗情報",
  "locationSourceUrl": "https://www.marukyo.co.jp/store/",
  "coordinateSource": "MapFan地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_051",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_052",
  "name": "トライアル 古賀花見店",
  "prefecture": "福岡県",
  "municipality": "古賀市",
  "address": "福岡県古賀市花見東四丁目13番28号",
  "category": "supermarket",
  "latitude": 33.749439,
  "longitude": 130.4718106,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "MapFan地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_052",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_053",
  "name": "ハンズマン 大野城店",
  "prefecture": "福岡県",
  "municipality": "大野城市",
  "address": "福岡県大野城市南大利1丁目5番1号",
  "category": "home-center",
  "latitude": 33.512638744406,
  "longitude": 130.47676223947,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "ハンズマン公式店舗情報",
  "locationSourceUrl": "https://www.handsman.co.jp/shop/",
  "coordinateSource": "MapFan地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_053",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_054",
  "name": "ハンズマン くさみ店",
  "prefecture": "福岡県",
  "municipality": "北九州市",
  "address": "福岡県北九州市小倉南区大字朽網字草見3914-21",
  "category": "home-center",
  "latitude": 33.807084,
  "longitude": 130.968045,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "ハンズマン公式店舗情報",
  "locationSourceUrl": "https://www.handsman.co.jp/shop/",
  "coordinateSource": "NAVITIME地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_054",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_055",
  "name": "カインズ 福岡新宮店",
  "prefecture": "福岡県",
  "municipality": "糟屋郡新宮町",
  "address": "福岡県糟屋郡新宮町中央駅前2-10-1",
  "category": "home-center",
  "latitude": 33.708859430944,
  "longitude": 130.45321758762,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "カインズ公式店舗情報",
  "locationSourceUrl": "https://map.cainz.com/",
  "coordinateSource": "MapFan地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_055",
  "targetBuildingId": null,
  "isDemo": false,
  "sampleRole": "large-comparison"
},
{
  "id": "target_056",
  "name": "ドラッグストアモリ 宗像店",
  "prefecture": "福岡県",
  "municipality": "宗像市",
  "address": "福岡県宗像市稲元2丁目3-17",
  "category": "drugstore",
  "parkingCapacity": 50,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_056",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_057",
  "name": "ジョイフル 福岡福津店",
  "prefecture": "福岡県",
  "municipality": "福津市",
  "address": "福岡県福津市宮司2丁目2-16",
  "category": "restaurant",
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_057",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_058",
  "name": "コメリパワー 飯塚店",
  "prefecture": "福岡県",
  "municipality": "飯塚市",
  "address": "福岡県飯塚市太郎丸1171番2",
  "category": "home-center",
  "latitude": 33.6134393,
  "longitude": 130.6702764,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "コメリ公式店舗情報",
  "locationSourceUrl": "https://www.komeri.com/shop/storeSearch/",
  "coordinateSource": "MapFan地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_058",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_059",
  "name": "道の駅 香春",
  "prefecture": "福岡県",
  "municipality": "田川郡香春町",
  "address": "福岡県田川郡香春町大字鏡山1870-1",
  "category": "roadside-station",
  "parkingCapacity": 86,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_059",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_060",
  "name": "マルキョウ 宗像店",
  "prefecture": "福岡県",
  "municipality": "宗像市",
  "address": "福岡県宗像市大字東郷字川向1169番地",
  "category": "supermarket",
  "latitude": 33.8090228,
  "longitude": 130.546045,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "マルキョウ公式店舗情報",
  "locationSourceUrl": "https://www.marukyo.co.jp/store/",
  "coordinateSource": "Yahoo!マップ地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_060",
  "targetBuildingId": null,
  "isDemo": false
},
// ----- 佐賀県 -----
{
  "id": "target_061",
  "name": "ドラッグストアモリ 神埼本堀店",
  "prefecture": "佐賀県",
  "municipality": "神埼市",
  "address": "佐賀県神埼市神埼町本堀3206-1",
  "category": "drugstore",
  "parkingCapacity": 73,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_061",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_062",
  "name": "ガスト 佐賀兵庫店",
  "prefecture": "佐賀県",
  "municipality": "佐賀市",
  "address": "佐賀県佐賀市兵庫南2丁目2-24",
  "category": "restaurant",
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_062",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_063",
  "name": "道の駅 大和 そよかぜ館",
  "prefecture": "佐賀県",
  "municipality": "佐賀市",
  "address": "佐賀県佐賀市大和町大字梅野805",
  "category": "roadside-station",
  "parkingCapacity": 56,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_063",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_064",
  "name": "TRIAL smart 伊万里店",
  "prefecture": "佐賀県",
  "municipality": "伊万里市",
  "address": "佐賀県伊万里市二里町大里甲2455-1",
  "category": "supermarket",
  "latitude": 33.272067,
  "longitude": 129.867657,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "公式MAP座標",
  "operatingStatus": "active",
  "layoutId": "target_064",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_065",
  "name": "トライアル 武雄富岡店",
  "prefecture": "佐賀県",
  "municipality": "武雄市",
  "address": "佐賀県武雄市武雄町富岡12431-1",
  "category": "supermarket",
  "latitude": 33.200691,
  "longitude": 130.034674,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "公式MAP座標",
  "operatingStatus": "active",
  "layoutId": "target_065",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_066",
  "name": "マルキョウ 神埼店",
  "prefecture": "佐賀県",
  "municipality": "神埼市",
  "address": "佐賀県神埼市神埼町枝ヶ里35-1",
  "category": "supermarket",
  "latitude": 33.30799543,
  "longitude": 130.37138127,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "マルキョウ公式店舗情報",
  "locationSourceUrl": "https://www.marukyo.co.jp/store/",
  "coordinateSource": "Mapion地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_066",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_067",
  "name": "マルキョウ 武雄店",
  "prefecture": "佐賀県",
  "municipality": "武雄市",
  "address": "佐賀県武雄市武雄町大字昭和7番",
  "category": "supermarket",
  "latitude": 33.19251261,
  "longitude": 130.02306679,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "マルキョウ公式店舗情報",
  "locationSourceUrl": "https://www.marukyo.co.jp/store/",
  "coordinateSource": "Mapion地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_067",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_068",
  "name": "MrMax 北茂安店",
  "prefecture": "佐賀県",
  "municipality": "三養基郡みやき町",
  "address": "佐賀県三養基郡みやき町大字白壁2228番地",
  "category": "discount-store",
  "latitude": 33.32856655,
  "longitude": 130.47662582,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "MrMax公式店舗情報",
  "locationSourceUrl": "https://www.mrmax.co.jp/shops/",
  "coordinateSource": "Mapion地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_068",
  "targetBuildingId": null,
  "isDemo": false,
  "sampleRole": "large-comparison"
},
{
  "id": "target_069",
  "name": "ホームプラザナフコ 武雄店",
  "prefecture": "佐賀県",
  "municipality": "武雄市",
  "address": "佐賀県武雄市武雄町武雄3921",
  "category": "home-center",
  "latitude": 33.18347807,
  "longitude": 130.01354209,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "ナフコ公式店舗情報",
  "locationSourceUrl": "https://www.nafco.life/shop_list/",
  "coordinateSource": "Mapion地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_069",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_070",
  "name": "ホームプラザナフコ 唐津店",
  "prefecture": "佐賀県",
  "municipality": "唐津市",
  "address": "佐賀県唐津市和多田西山9-5",
  "category": "home-center",
  "latitude": 33.42958176,
  "longitude": 129.98082724,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "ナフコ公式店舗情報",
  "locationSourceUrl": "https://www.nafco.life/shop_list/",
  "coordinateSource": "Mapion地点（公式住所照合・同一住所の家具館地点）",
  "operatingStatus": "active",
  "layoutId": "target_070",
  "targetBuildingId": null,
  "isDemo": false
},
// ----- 長崎県 -----
{
  "id": "target_071",
  "name": "ドラッグストアコスモス 大潟店",
  "prefecture": "長崎県",
  "municipality": "佐世保市",
  "address": "長崎県佐世保市大潟町60-201",
  "category": "drugstore",
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_071",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_072",
  "name": "ガスト 長崎大浦海岸店",
  "prefecture": "長崎県",
  "municipality": "長崎市",
  "address": "長崎県長崎市常盤町1-50",
  "category": "restaurant",
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_072",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_073",
  "name": "道の駅 彼杵の荘",
  "prefecture": "長崎県",
  "municipality": "東彼杵郡東彼杵町",
  "address": "長崎県東彼杵郡東彼杵町彼杵宿郷747-2",
  "category": "roadside-station",
  "parkingCapacity": 125,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_073",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_074",
  "name": "トライアル 佐世保大和店",
  "prefecture": "長崎県",
  "municipality": "佐世保市",
  "address": "長崎県佐世保市大和町65-2",
  "category": "supermarket",
  "latitude": 33.155115,
  "longitude": 129.7493534,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "MapFan地点（TRIAL公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_074",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_075",
  "name": "トライアル 島原店",
  "prefecture": "長崎県",
  "municipality": "島原市",
  "address": "長崎県島原市前浜町丙227",
  "category": "supermarket",
  "latitude": 32.80797713,
  "longitude": 130.35799213,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "Mapion地点（TRIAL公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_075",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_076",
  "name": "トライアル 大村店",
  "prefecture": "長崎県",
  "municipality": "大村市",
  "address": "長崎県大村市松並2丁目92-1",
  "category": "supermarket",
  "latitude": 32.92372796,
  "longitude": 129.9478489,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "Mapion地点（TRIAL公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_076",
  "targetBuildingId": null,
  "isDemo": false,
  "sampleRole": "large-comparison"
},
{
  "id": "target_077",
  "name": "トライアル 諫早店",
  "prefecture": "長崎県",
  "municipality": "諫早市",
  "address": "長崎県諫早市長野町1690-8",
  "category": "supermarket",
  "latitude": 32.83059658,
  "longitude": 130.08053372,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "Mapion地点（TRIAL公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_077",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_078",
  "name": "トライアル 時津店",
  "prefecture": "長崎県",
  "municipality": "西彼杵郡時津町",
  "address": "長崎県西彼杵郡時津町日並郷3613",
  "category": "supermarket",
  "latitude": 32.8461022,
  "longitude": 129.8341358,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "MapFan地点（TRIAL公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_078",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_079",
  "name": "マルキョウ 大宮店",
  "prefecture": "長崎県",
  "municipality": "佐世保市",
  "address": "長崎県佐世保市大宮町2-4 サクセスビル",
  "category": "supermarket",
  "latitude": 33.1568865,
  "longitude": 129.7378939,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "マルキョウ公式店舗情報",
  "locationSourceUrl": "https://www.marukyo.co.jp/store/",
  "coordinateSource": "MapFan地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_079",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_080",
  "name": "ホームプラザナフコ 時津店",
  "prefecture": "長崎県",
  "municipality": "西彼杵郡時津町",
  "address": "長崎県西彼杵郡時津町日並郷2195-53",
  "category": "home-center",
  "latitude": 32.84950899,
  "longitude": 129.83003103,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "ナフコ公式店舗情報",
  "locationSourceUrl": "https://www.nafco.life/shop_list/",
  "coordinateSource": "Mapion地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_080",
  "targetBuildingId": null,
  "isDemo": false
},
// ----- 熊本県 -----
{
  "id": "target_081",
  "name": "ドラッグストアコスモス 大津バイパス店",
  "prefecture": "熊本県",
  "municipality": "菊池郡大津町",
  "address": "熊本県菊池郡大津町大津1311-1",
  "category": "drugstore",
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_081",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_082",
  "name": "ガスト 熊本戸島店",
  "prefecture": "熊本県",
  "municipality": "熊本市",
  "address": "熊本県熊本市東区戸島西4丁目2-53",
  "category": "restaurant",
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_082",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_083",
  "name": "道の駅 大津",
  "prefecture": "熊本県",
  "municipality": "菊池郡大津町",
  "address": "熊本県菊池郡大津町大字引水759",
  "category": "roadside-station",
  "parkingCapacity": 130,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_083",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_084",
  "name": "メガセンタートライアル 荒尾店",
  "prefecture": "熊本県",
  "municipality": "荒尾市",
  "address": "熊本県荒尾市海陽町二丁目1番地1",
  "category": "supermarket",
  "latitude": 32.99297159,
  "longitude": 130.42965609,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "Mapion地点（TRIAL公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_084",
  "targetBuildingId": null,
  "isDemo": false,
  "sampleRole": "large-comparison"
},
{
  "id": "target_085",
  "name": "トライアル 宇土店",
  "prefecture": "熊本県",
  "municipality": "宇土市",
  "address": "熊本県宇土市善道寺町綾織22-1",
  "category": "supermarket",
  "latitude": 32.6792476,
  "longitude": 130.6744343,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "MapFan地点（TRIAL公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_085",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_086",
  "name": "トライアル 八代店",
  "prefecture": "熊本県",
  "municipality": "八代市",
  "address": "熊本県八代市新開町3-15",
  "category": "supermarket",
  "latitude": 32.50798123,
  "longitude": 130.57900833,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "Mapion地点（TRIAL公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_086",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_087",
  "name": "カインズ 熊本宇土店",
  "prefecture": "熊本県",
  "municipality": "宇土市",
  "address": "熊本県宇土市三拾町171",
  "category": "home-center",
  "latitude": 32.6950313,
  "longitude": 130.6698989,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "カインズ公式店舗情報",
  "locationSourceUrl": "https://map.cainz.com/",
  "coordinateSource": "MapFan地点（カインズ公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_087",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_088",
  "name": "マルキョウ 植木店",
  "prefecture": "熊本県",
  "municipality": "熊本市",
  "address": "熊本県熊本市北区植木町岩野266-5",
  "category": "supermarket",
  "latitude": 32.9021716,
  "longitude": 130.693191,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "マルキョウ公式店舗情報",
  "locationSourceUrl": "https://www.marukyo.co.jp/store/",
  "coordinateSource": "Yahoo!マップ地点（マルキョウ公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_088",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_089",
  "name": "マルキョウ 合志店",
  "prefecture": "熊本県",
  "municipality": "合志市",
  "address": "熊本県合志市幾久富1909-48",
  "category": "supermarket",
  "latitude": 32.86424345,
  "longitude": 130.768771,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "マルキョウ公式店舗情報",
  "locationSourceUrl": "https://www.marukyo.co.jp/store/",
  "coordinateSource": "Mapion地点（マルキョウ公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_089",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_090",
  "name": "マルキョウ 玉名店",
  "prefecture": "熊本県",
  "municipality": "玉名市",
  "address": "熊本県玉名市岱明町野口197",
  "category": "supermarket",
  "latitude": 32.92848108,
  "longitude": 130.53966553,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "マルキョウ公式店舗情報",
  "locationSourceUrl": "https://www.marukyo.co.jp/store/",
  "coordinateSource": "MapFan地点（マルキョウ公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_090",
  "targetBuildingId": null,
  "isDemo": false
},
// ----- 大分県 -----
{
  "id": "target_091",
  "name": "ドラッグストアコスモス 大分新川店",
  "prefecture": "大分県",
  "municipality": "大分市",
  "address": "大分県大分市新川西2丁目1-1",
  "category": "drugstore",
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_091",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_092",
  "name": "ガスト 大分森町店",
  "prefecture": "大分県",
  "municipality": "大分市",
  "address": "大分県大分市大字森町238-1",
  "category": "restaurant",
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_092",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_093",
  "name": "道の駅 童話の里くす",
  "prefecture": "大分県",
  "municipality": "玖珠郡玖珠町",
  "address": "大分県玖珠郡玖珠町大字帆足2121",
  "category": "roadside-station",
  "parkingCapacity": 118,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_093",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_094",
  "name": "トライアル 敷戸店",
  "prefecture": "大分県",
  "municipality": "大分市",
  "address": "大分県大分市敷戸台1丁目1-8",
  "category": "supermarket",
  "latitude": 33.188955,
  "longitude": 131.616469,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "Yahoo!マップ地点（TRIAL公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_094",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_095",
  "name": "トライアル 日田店",
  "prefecture": "大分県",
  "municipality": "日田市",
  "address": "大分県日田市北友田3丁目2530-1",
  "category": "supermarket",
  "latitude": 33.3237611514,
  "longitude": 130.9021504576,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "Yahoo!マップ地点（TRIAL公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_095",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_096",
  "name": "トライアル 別府店",
  "prefecture": "大分県",
  "municipality": "別府市",
  "address": "大分県別府市竹の内町49番69号",
  "category": "supermarket",
  "latitude": 33.30339922,
  "longitude": 131.46193597,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "Mapion地点（TRIAL公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_096",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_097",
  "name": "トライアル 中津店",
  "prefecture": "大分県",
  "municipality": "中津市",
  "address": "大分県中津市大字下池永字熊本153-1",
  "category": "supermarket",
  "latitude": 33.5870785255,
  "longitude": 131.2138321491,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "Yahoo!マップ地点（TRIAL公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_097",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_098",
  "name": "マルキョウ 皆春店",
  "prefecture": "大分県",
  "municipality": "大分市",
  "address": "大分県大分市大字皆春字美操318番地の1",
  "category": "supermarket",
  "latitude": 33.2337216,
  "longitude": 131.6739132,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "マルキョウ公式店舗情報",
  "locationSourceUrl": "https://www.marukyo.co.jp/store/",
  "coordinateSource": "Yahoo!マップ地点（マルキョウ公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_098",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_099",
  "name": "マルキョウ 中津店",
  "prefecture": "大分県",
  "municipality": "中津市",
  "address": "大分県中津市下池永115-1",
  "category": "supermarket",
  "latitude": 33.5896254,
  "longitude": 131.2131837,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "マルキョウ公式店舗情報",
  "locationSourceUrl": "https://www.marukyo.co.jp/store/",
  "coordinateSource": "Yahoo!マップ地点（マルキョウ公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_099",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_100",
  "name": "MrMax 宇佐店",
  "prefecture": "大分県",
  "municipality": "宇佐市",
  "address": "大分県宇佐市大字法鏡寺500",
  "category": "discount-store",
  "latitude": 33.5262354,
  "longitude": 131.3499422,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "MrMax公式店舗情報",
  "locationSourceUrl": "https://www.mrmax.co.jp/shops/",
  "coordinateSource": "MapFan地点（MrMax公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_100",
  "targetBuildingId": null,
  "isDemo": false,
  "sampleRole": "large-comparison"
},
// ----- 宮崎県 -----
{
  "id": "target_101",
  "name": "ドラッグストアモリ 恒久店",
  "prefecture": "宮崎県",
  "municipality": "宮崎市",
  "address": "宮崎県宮崎市大字恒久4378-2",
  "category": "drugstore",
  "parkingCapacity": 63,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_101",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_102",
  "name": "ジョイフル 宮崎大塚店",
  "prefecture": "宮崎県",
  "municipality": "宮崎市",
  "address": "宮崎県宮崎市大塚町宮田2942-1",
  "category": "restaurant",
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_102",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_103",
  "name": "ハンズマン 柳丸店",
  "prefecture": "宮崎県",
  "municipality": "宮崎市",
  "address": "宮崎県宮崎市柳丸町143番地2",
  "category": "home-center",
  "latitude": 31.9271201,
  "longitude": 131.4356064,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "ハンズマン公式店舗情報",
  "locationSourceUrl": "https://www.handsman.co.jp/shop/",
  "coordinateSource": "MapFan地点（ハンズマン公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_103",
  "targetBuildingId": null,
  "isDemo": false,
  "sampleRole": "large-comparison"
},
{
  "id": "target_104",
  "name": "道の駅 高岡ビタミン館",
  "prefecture": "宮崎県",
  "municipality": "宮崎市",
  "address": "宮崎県宮崎市高岡町花見304-5",
  "category": "roadside-station",
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_104",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_105",
  "name": "トライアル 加納店",
  "prefecture": "宮崎県",
  "municipality": "宮崎市",
  "address": "宮崎県宮崎市清武町加納乙382番地6",
  "category": "supermarket",
  "latitude": 31.878582615988048,
  "longitude": 131.40537184201523,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "Yahoo!マップ地点（TRIAL公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_105",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_106",
  "name": "トライアル 宮崎恒久店",
  "prefecture": "宮崎県",
  "municipality": "宮崎市",
  "address": "宮崎県宮崎市大字恒久1527-1",
  "category": "supermarket",
  "latitude": 31.8888945,
  "longitude": 131.423833,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "MapFan地点（TRIAL公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_106",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_107",
  "name": "トライアル 都城都北店",
  "prefecture": "宮崎県",
  "municipality": "都城市",
  "address": "宮崎県都城市都北町717-3",
  "category": "supermarket",
  "latitude": 31.75840504,
  "longitude": 131.09369529,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "Yahoo!マップ地点（TRIAL公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_107",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_108",
  "name": "トライアル 小林店",
  "prefecture": "宮崎県",
  "municipality": "小林市",
  "address": "宮崎県小林市堤字西ノ原2907-1",
  "category": "supermarket",
  "latitude": 31.983812,
  "longitude": 130.9917694,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "MapFan地点（TRIAL公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_108",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_109",
  "name": "メガセンタートライアル 日向店",
  "prefecture": "宮崎県",
  "municipality": "日向市",
  "address": "宮崎県日向市都町10754-11",
  "category": "supermarket",
  "latitude": 32.42687682,
  "longitude": 131.6272115,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "Yahoo!マップ地点（TRIAL公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_109",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_110",
  "name": "トライアル 日南店",
  "prefecture": "宮崎県",
  "municipality": "日南市",
  "address": "宮崎県日南市平野字深坪2559-1",
  "category": "supermarket",
  "latitude": 31.595844,
  "longitude": 131.39153,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "Yahoo!マップ地点（TRIAL公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_110",
  "targetBuildingId": null,
  "isDemo": false
},
// ----- 鹿児島県 -----
{
  "id": "target_111",
  "name": "ハンズマン 宇宿店",
  "prefecture": "鹿児島県",
  "municipality": "鹿児島市",
  "address": "鹿児島県鹿児島市宇宿2丁目14番5号",
  "category": "home-center",
  "latitude": 31.5423913,
  "longitude": 130.5415956,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "ハンズマン公式店舗情報",
  "locationSourceUrl": "https://www.handsman.co.jp/shop/",
  "coordinateSource": "MapFan地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_111",
  "targetBuildingId": null,
  "isDemo": false,
  "sampleRole": "large-comparison"
},
{
  "id": "target_112",
  "name": "ドラッグストアコスモス 鹿児島宇宿店",
  "prefecture": "鹿児島県",
  "municipality": "鹿児島市",
  "address": "鹿児島県鹿児島市宇宿9丁目10-1",
  "category": "drugstore",
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_112",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_113",
  "name": "ジョイフル 鹿児島坂之上店",
  "prefecture": "鹿児島県",
  "municipality": "鹿児島市",
  "address": "鹿児島県鹿児島市光山2丁目2-20",
  "category": "restaurant",
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_113",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_114",
  "name": "道の駅 たるみず",
  "prefecture": "鹿児島県",
  "municipality": "垂水市",
  "address": "鹿児島県垂水市牛根麓1038-1",
  "category": "roadside-station",
  "parkingCapacity": 123,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-29",
  "locationSource": "公開店舗情報・施設公式情報で住所確認",
  "coordinateSource": "確認済み住所から国土地理院住所検索",
  "operatingStatus": "active",
  "facilityRevision": 4,
  "replacementReason": "大型駐車場偏重を避け、200台以内を目安に施設種別を多様化",
  "sampleRole": "small-medium-diverse",
  "layoutId": "target_114",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_115",
  "name": "トライアル 指宿店",
  "prefecture": "鹿児島県",
  "municipality": "指宿市",
  "address": "鹿児島県指宿市西方4558番地",
  "category": "supermarket",
  "latitude": 31.2718006045,
  "longitude": 130.6251749027,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "MapFan地図更新情報（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_115",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_116",
  "name": "トライアル 鹿屋店",
  "prefecture": "鹿児島県",
  "municipality": "鹿屋市",
  "address": "鹿児島県鹿屋市笠之原町1950-1",
  "category": "supermarket",
  "latitude": 31.3982586,
  "longitude": 130.8867193,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "MapFan地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_116",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_117",
  "name": "ホームプラザナフコ 谷山店",
  "prefecture": "鹿児島県",
  "municipality": "鹿児島市",
  "address": "鹿児島県鹿児島市下福元町6723-2",
  "category": "home-center",
  "latitude": 31.483409,
  "longitude": 130.510925,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "ナフコ公式店舗情報",
  "locationSourceUrl": "https://www.nafco.life/shop_list/1630/",
  "coordinateSource": "NAVITIME地点（公式住所照合）",
  "operatingStatus": "active",
  "facilityRevision": 2,
  "replacementReason": "旧対象のトライアル鹿屋上野町店は固定座標の複数資料照合が完了しなかったため置換",
  "layoutId": "target_117",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_118",
  "name": "トライアル 出水黄金店",
  "prefecture": "鹿児島県",
  "municipality": "出水市",
  "address": "鹿児島県出水市黄金町562",
  "category": "supermarket",
  "latitude": 32.1030355,
  "longitude": 130.3428956,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "MapFan地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_118",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_119",
  "name": "トライアル 加治木店",
  "prefecture": "鹿児島県",
  "municipality": "姶良市",
  "address": "鹿児島県姶良市加治木町反土字上古川2864-1",
  "category": "supermarket",
  "latitude": 31.7456386,
  "longitude": 130.6564682,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "TRIAL公式店舗情報",
  "locationSourceUrl": "https://www.trial-net.co.jp/shops/",
  "coordinateSource": "MapFan地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_119",
  "targetBuildingId": null,
  "isDemo": false
},
{
  "id": "target_120",
  "name": "ホームプラザナフコ 鹿児島東開店",
  "prefecture": "鹿児島県",
  "municipality": "鹿児島市",
  "address": "鹿児島県鹿児島市東開町4-15",
  "category": "home-center",
  "latitude": 31.5310573,
  "longitude": 130.5365604,
  "locationVerified": true,
  "locationVerificationDate": "2026-09-28",
  "locationSource": "ナフコ公式店舗情報",
  "locationSourceUrl": "https://www.nafco.life/shop_list/",
  "coordinateSource": "MapFan地点（公式住所照合）",
  "operatingStatus": "active",
  "layoutId": "target_120",
  "targetBuildingId": null,
  "isDemo": false
}
]);
